In [3]:
import os
import pandas as pd

In [4]:
%cd D:/Project4NUS

D:\Project4NUS

# **1.Preprocessing of data from Whoscored_summary,Whoscored_defensive,Whoscored_offensive**

In [5]:
#raw data
df_defend = pd.read_csv(r'.\Whoscored\raw\Whoscored_defensive.csv')
df_offend = pd.read_csv(r'.\Whoscored\raw\Whoscored_offensive.csv')
df_summary = pd.read_csv(r'.\Whoscored\raw\Whoscored_summary.csv')

In [6]:
# Summary different tournaments
unique_values = df_summary['Tournament'].unique()  
unique_count = len(unique_values)  

print(f"There are {unique_count} tournaments in Whoscored Dataset，they are {unique_values}")

There are 36 tournaments in Whoscored Dataset，they are ['UEL' 'GB' 'ACoN' 'GB2' 'UCL' 'SLL' 'UNL' 'UEC' nan 'EPL' 'ECQ' 'ECS'
 'USC' 'EFLC' 'WCQ' 'NE' 'ICA' 'FL1' 'ALP' 'WC' 'IEU' 'ISA' 'PLN' 'RPL'
 'EC' 'BSA' 'UMLS' 'BJL' 'TS' 'GBQ' 'SP' 'EL1' 'CSL' 'SA' 'EL2' 'ICC']

In [7]:
# Summary different tournaments
unique_values_1 = df_summary['name'].unique()  
unique_values_2 = df_defend['name'].unique()  
unique_values_3 = df_offend['name'].unique()  
unique_count_1 = len(unique_values_1)  
unique_count_2 = len(unique_values_2) 
unique_count_3 = len(unique_values_3) 

print(f"players:{unique_count_1} in Whoscored_sum,{unique_count_2} in Whoscored_de,{unique_count_3} in Whoscored_of")

players:696 in Whoscored_sum,703 in Whoscored_de,773 in Whoscored_of

**1.1 Drop irrelavant columns(Team_link,Tournament_link)**

The columns "Team_link","Tournament_link" are simply url of logos of team and tournament,which is relavant to our research

In [8]:
df_defend = df_defend.drop(df_defend.columns[[2, 4]], axis=1)
df_offend = df_offend.drop(df_offend.columns[[2, 4]], axis=1)
df_summary = df_summary.drop(df_summary.columns[[2, 4]], axis=1)

**1.2Drop irrelavant rows**

In [9]:
#drop irrelavant rows(when the value of column'season'==Total/average) 
df_defend_cleaned = df_defend[df_defend['Season'] != 'Total / Average']
df_offend_cleaned = df_offend[df_offend['Season'] != 'Total / Average']
df_summary_cleaned = df_summary[df_summary['Season'] != 'Total / Average']
# save for backup
#df_defend_cleaned.to_csv(r'D:\Project4NUS\Whoscored\raw\Whoscored_defensive_cleaned.csv', index=False)
#df_offend_cleaned.to_csv(r'D:\Project4NUS\Whoscored\raw\Whoscored_offensive_cleaned.csv', index=False)
#df_summary_cleaned.to_csv(r'D:\Project4NUS\Whoscored\raw\Whoscored_summary_cleaned.csv', index=False)
#df_defend
#df_offend
#df_summary
df_defend_cleaned
#df_offend_cleaned
#df_summary_cleaned

,name,Season,Team,Tournament,Apps,Mins,Tackles,Inter,Fouls,Offsides,Clear,Drb,Blocks,OwnG,Rating
0,\n Omar Marmoush,2024/2025,Eintracht Frankfurt,UEL,2,153.0,1.5\t,0.5\t,1\t,-\t,-\t,-\t,-\t,-\t,7.23
1,\n Omar Marmoush,2024/2025,Eintracht Frankfurt,GB,6,503.0,0.8\t,0.2\t,0.2\t,-\t,0.2\t,0.3\t,0.2\t,-\t,8.49
2,\n Omar Marmoush,2023,Egypt,ACoN,2(2),235.0,1.5\t,0.3\t,1\t,-\t,0.3\t,0.3\t,-\t,-\t,7.21
3,\n Omar Marmoush,2023/2024,Eintracht Frankfurt,GB,27(2),2311.0,0.7\t,0.4\t,1\t,-\t,0.2\t,0.3\t,-\t,-\t,7.11
4,\n Omar Marmoush,2022/2023,Wolfsburg,GB,15(18),1480.0,0.5\t,0.2\t,0.9\t,-\t,0.1\t,0.4\t,-\t,-\t,6.51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9866,\n Fran Beltrán,2022/2023,Celta Vigo,SLL,33(3),2864.0,0.9\t,1.5\t,0.7\t,-\t,0.9\t,1.1\t,0.1\t,-\t,6.49
9867,\n Fran Beltrán,2021/2022,Celta Vigo,SLL,31(6),2611.0,1.5\t,0.9\t,0.5\t,-\t,0.8\t,1.1\t,0.1\t,-\t,6.61
9868,\n Fran Beltrán,2020/2021,Celta Vigo,SLL,13(19),1392.0,0.9\t,0.5\t,0.5\t,-\t,0.7\t,0.5\t,-\t,-\t,6.37
9869,\n Fran Beltrán,2019/2020,Celta Vigo,SLL,22(6),1835.0,1.1\t,0.5\t,0.4\t,-\t,0.5\t,0.9\t,-\t,-\t,6.37
9870,\n Fran Beltrán,2018/2019,Celta Vigo,SLL,16(14),1513.0,0.8\t,0.6\t,0.4\t,-\t,0.5\t,0.6\t,0.1\t,-\t,6.30

**1.3 Drop rows whose tournament is not in "GB，EPL，SLL，FL1，ISA"**

In [10]:
valid_tournaments = ['GB', 'EPL', 'SLL', 'FL1', 'ISA']
df_defend_filtered = df_defend_cleaned[df_defend_cleaned['Tournament'].isin(valid_tournaments)]
df_offend_filtered = df_offend_cleaned[df_offend_cleaned['Tournament'].isin(valid_tournaments)]
df_summary_filtered = df_summary_cleaned[df_summary_cleaned['Tournament'].isin(valid_tournaments)]
# save for backup
#df_defend_filtered.to_csv(r'D:\Project4NUS\Whoscored\raw\Whoscored_defensive_filtered.csv', index=False)
#df_offend_filtered.to_csv(r'D:\Project4NUS\Whoscored\raw\Whoscored_offensive_filtered.csv', index=False)
#df_summary_filtered.to_csv(r'D:\Project4NUS\Whoscored\raw\Whoscored_summary_filtered.csv', index=False)

#print(df_defend_filtered.head())
#print(df_offend_filtered.head())
#print(df_summary_filtered.head())

#to see if "Season" column is all in the format"20xx/20xx"
abnormal_defend = df_defend_filtered[~df_defend_filtered['Season'].str.contains('/')]
print(abnormal_defend)

abnormal_offend = df_offend_filtered[~df_offend_filtered['Season'].str.contains('/')]
print(abnormal_offend)

abnormal_summary = df_summary_filtered[~df_summary_filtered['Season'].str.contains('/')]
print(abnormal_summary)

#We prove that all "Season" column is in the format"20xx/20xx" after filtering tournament!

Empty DataFrame
Columns: [name, Season, Team, Tournament, Apps, Mins, Tackles, Inter, Fouls, Offsides, Clear, Drb, Blocks, OwnG, Rating]
Index: []
Empty DataFrame
Columns: [name, Season, Team, Tournament, Apps, Mins, Goals, Assists, SpG, KeyP, Drb, Fouled, Off, Disp, UnsTch, Rating]
Index: []
Empty DataFrame
Columns: [name, Season, Team, Tournament, Apps, Mins, Goals, Assists, Yel, SpG, PS, AerialsWon, MotM, Rating]
Index: []

In [11]:
# Summary different tournaments
unique_values_4 = df_summary_filtered['name'].unique()  
unique_values_5 = df_defend_filtered['name'].unique()  
unique_values_6 = df_offend_filtered['name'].unique()  
unique_count_4 = len(unique_values_4)  
unique_count_5 = len(unique_values_5) 
unique_count_6 = len(unique_values_6) 

print(f"players:{unique_count_4} in Whoscored_sum,{unique_count_5} in Whoscored_de,{unique_count_6} in Whoscored_of")

players:696 in Whoscored_sum,703 in Whoscored_de,773 in Whoscored_of

**1.4 Merge Defend,Offend,Summary to one dataset(merge index:player name and Tournament)**

In [12]:
df_summary_filtered.head()

,name,Season,Team,Tournament,Apps,Mins,Goals,Assists,Yel,SpG,PS,AerialsWon,MotM,Rating
1,\n Omar Marmoush,2024/2025,Eintracht Frankfurt,GB,5,413,6\t,3\t,-\t,5.2\t,84.4\t,0.6\t,2\t,8.34
3,\n Omar Marmoush,2023/2024,Eintracht Frankfurt,GB,27(2),2311,12\t,6\t,7\t,2.7\t,73.4\t,1\t,4\t,7.11
4,\n Omar Marmoush,2022/2023,Wolfsburg,GB,15(18),1480,5\t,1\t,2\t,1.5\t,68.5\t,1.3\t,1\t,6.51
6,\n Omar Marmoush,2021/2022,Stuttgart,GB,19(2),1584,3\t,5\t,3\t,2.3\t,71.2\t,1.3\t,1\t,6.95
7,\n Omar Marmoush,2021/2022,Wolfsburg,GB,0(2),22,-\t,-\t,-\t,0.5\t,75\t,0.5\t,-\t,6.03

In [13]:
df_offend_filtered.head()

,name,Season,Team,Tournament,Apps,Mins,Goals,Assists,SpG,KeyP,Drb,Fouled,Off,Disp,UnsTch,Rating
1,\n Omar Marmoush,2024/2025,Eintracht Frankfurt,GB,6,503.0,8\t,4\t,4.7\t,2.3\t,2\t,3.2\t,0.5\t,2.2\t,3.2\t,8.49
3,\n Omar Marmoush,2023/2024,Eintracht Frankfurt,GB,27(2),2311.0,12\t,6\t,2.7\t,1.4\t,1.3\t,2.6\t,0.4\t,2\t,3.4\t,7.11
4,\n Omar Marmoush,2022/2023,Wolfsburg,GB,15(18),1480.0,5\t,1\t,1.5\t,0.3\t,1.2\t,1\t,0.4\t,1.3\t,2.3\t,6.51
6,\n Omar Marmoush,2021/2022,Stuttgart,GB,19(2),1584.0,3\t,5\t,2.3\t,1.5\t,2.1\t,2.7\t,0.3\t,2\t,4.1\t,6.95
7,\n Omar Marmoush,2021/2022,Wolfsburg,GB,0(2),22.0,-\t,-\t,0.5\t,0.5\t,-\t,-\t,-\t,-\t,0.5\t,6.03

In [14]:
df_defend_filtered.head()

,name,Season,Team,Tournament,Apps,Mins,Tackles,Inter,Fouls,Offsides,Clear,Drb,Blocks,OwnG,Rating
1,\n Omar Marmoush,2024/2025,Eintracht Frankfurt,GB,6,503.0,0.8\t,0.2\t,0.2\t,-\t,0.2\t,0.3\t,0.2\t,-\t,8.49
3,\n Omar Marmoush,2023/2024,Eintracht Frankfurt,GB,27(2),2311.0,0.7\t,0.4\t,1\t,-\t,0.2\t,0.3\t,-\t,-\t,7.11
4,\n Omar Marmoush,2022/2023,Wolfsburg,GB,15(18),1480.0,0.5\t,0.2\t,0.9\t,-\t,0.1\t,0.4\t,-\t,-\t,6.51
6,\n Omar Marmoush,2021/2022,Wolfsburg,GB,0(2),22.0,-\t,-\t,-\t,-\t,-\t,-\t,-\t,-\t,6.03
7,\n Omar Marmoush,2021/2022,Stuttgart,GB,19(2),1584.0,1.2\t,0.3\t,1.6\t,-\t,0.2\t,0.8\t,-\t,-\t,6.95

In [15]:
#Rename the 'rating' column of each dataset
df_defend_filtered = df_defend_filtered.rename(columns={'Rating': 'Rating_defend','Drb': 'Drb_defend'})
df_offend_filtered = df_offend_filtered.rename(columns={'Rating': 'Rating_offend','Drb': 'Drb_offend'})#,'Goals' : 'Goals_offend'})
df_summary_filtered = df_summary_filtered.rename(columns={'Rating': 'Rating_summary'})#,'Goals' : 'Goals_summary'})

In [16]:
#First Merge Summary and Offensive to SUOF,'name','Season','Team','Tournament','Apps','Mins','Goals','Assists','SpG'
merged_df_suof = pd.merge(df_summary_filtered, df_offend_filtered, on=['name','Season','Team','Tournament','Apps','Mins','Assists','SpG','Goals']
                                                                       , how='inner')

In [17]:
merged_df_suof
merged_df_suof.to_csv(r'D:\Project4NUS\Whoscored\Whoscored_three_combined\Whoscored_suof.csv', index=False)

In [18]:
#Then Merge SUOF to Defend
merged_all = pd.merge(merged_df_suof, df_defend_filtered, on=['name','Season','Team','Tournament','Apps','Mins']
                                                              , how='inner')
#merged_all
#check if there is repeating column names
merged_all.columns

Index(['name', 'Season', 'Team', 'Tournament', 'Apps', 'Mins', 'Goals',
       'Assists', 'Yel', 'SpG', 'PS', 'AerialsWon', 'MotM', 'Rating_summary',
       'KeyP', 'Drb_offend', 'Fouled', 'Off', 'Disp', 'UnsTch',
       'Rating_offend', 'Tackles', 'Inter', 'Fouls', 'Offsides', 'Clear',
       'Drb_defend', 'Blocks', 'OwnG', 'Rating_defend'],
      dtype='object')

In [19]:
unique_values_7 = merged_all['name'].unique()  
unique_count_7 = len(unique_values_7)  

print(f"There are {unique_count_7} players in Whoscored_Merge_data")

There are 561 players in Whoscored_Merge_data

In [21]:
merged_all.to_csv(r'.\Whoscored\Whoscored_three_combined\Whoscored_finaldata.csv', index=False)

**1.5 Mapping whoscored data to FIFA based on season**

**Whoscored_23 means mapping to FIFA_23(Season in Whoscored is 2021/2022)**

In [22]:
Whoscored_23 = merged_all[merged_all['Season'] == '2021/2022']
Whoscored_22 = merged_all[merged_all['Season'] == '2020/2021']
Whoscored_21 = merged_all[merged_all['Season'] == '2019/2020']
Whoscored_20 = merged_all[merged_all['Season'] == '2018/2019']
Whoscored_19 = merged_all[merged_all['Season'] == '2017/2018']
Whoscored_18 = merged_all[merged_all['Season'] == '2016/2017']
Whoscored_17 = merged_all[merged_all['Season'] == '2015/2016']

In [23]:
Whoscored_17.columns

Index(['name', 'Season', 'Team', 'Tournament', 'Apps', 'Mins', 'Goals',
       'Assists', 'Yel', 'SpG', 'PS', 'AerialsWon', 'MotM', 'Rating_summary',
       'KeyP', 'Drb_offend', 'Fouled', 'Off', 'Disp', 'UnsTch',
       'Rating_offend', 'Tackles', 'Inter', 'Fouls', 'Offsides', 'Clear',
       'Drb_defend', 'Blocks', 'OwnG', 'Rating_defend'],
      dtype='object')

In [25]:
#save files
Whoscored_23.to_csv(r'.\Whoscored\Whoscored_map_to_FIFA\Whoscored_23.csv', index=False)
Whoscored_22.to_csv(r'.\Whoscored\Whoscored_map_to_FIFA\Whoscored_22.csv', index=False)
Whoscored_21.to_csv(r'.\Whoscored\Whoscored_map_to_FIFA\Whoscored_21.csv', index=False)
Whoscored_20.to_csv(r'.\Whoscored\Whoscored_map_to_FIFA\Whoscored_20.csv', index=False)
Whoscored_19.to_csv(r'.\Whoscored\Whoscored_map_to_FIFA\Whoscored_19.csv', index=False)
Whoscored_18.to_csv(r'.\Whoscored\Whoscored_map_to_FIFA\Whoscored_18.csv', index=False)
Whoscored_17.to_csv(r'.\Whoscored\Whoscored_map_to_FIFA\Whoscored_17.csv', index=False)

# **2.Preprocessing of data from FIFA**

In [26]:
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [27]:
#raw data
FIFA_17 = pd.read_csv(r'D:\Project4NUS\FIFA\FIFA_cleaned\17.csv')
FIFA_17.head()

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Preferred Foot,International Reputation,...,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Best Position,Best Overall Rating
0,176580,L. Suárez,29,Uruguay,92,92,FC Barcelona,_83M,Right,5,...,30,45,38,27,25,31,33,37,ST,88
1,178518,R. Nainggolan,28,Belgium,86,86,Roma,_37.5M,Right,3,...,78,85,88,11,11,14,8,11,CDM,84
2,181872,A. Vidal,29,Chile,87,87,FC Bayern München,_41.5M,Right,4,...,76,89,84,4,2,4,2,4,CDM,85
3,197445,D. Alaba,24,Austria,86,89,FC Bayern München,_41.5M,Left,4,...,81,83,83,5,7,14,15,9,LB,84
4,195864,P. Pogba,23,France,88,94,Manchester United,_71.5M,Right,4,...,68,73,73,5,6,2,4,3,CAM,85

**2.1 Drop irrelavant columns(photo,flag,potential,club logo,wage,special,real face,jersey number,joined,loaned from)**

In [28]:
import scipy.stats as stats

fifa17_df = pd.read_csv(r'D:\Project4NUS\FIFA\FIFA_cleaned\17.csv')
fifa18_df = pd.read_csv(r'D:\Project4NUS\FIFA\FIFA_cleaned\18.csv')
fifa19_df = pd.read_csv(r'D:\Project4NUS\FIFA\FIFA_cleaned\19.csv')
fifa20_df = pd.read_csv(r'D:\Project4NUS\FIFA\FIFA_cleaned\20.csv')
fifa21_df = pd.read_csv(r'D:\Project4NUS\FIFA\raw\FIFA21_official_data.csv')
fifa22_df = pd.read_csv(r'D:\Project4NUS\FIFA\raw\FIFA22_official_data.csv')
fifa23_df = pd.read_csv(r'D:\Project4NUS\FIFA\raw\FIFA23_official_data.csv')
#fifa21_df = pd.read_csv(r'D:\Project4NUS\FIFA\FIFA_cleaned\21.csv')
#fifa22_df = pd.read_csv(r'D:\Project4NUS\FIFA\FIFA_cleaned\22.csv')
#fifa23_df = pd.read_csv(r'D:\Project4NUS\FIFA\FIFA_cleaned\23.csv')

In [237]:
fifa21_df=fifa21_df.drop(columns=['Club Logo','Flag','Jersey Number','Joined','Loaned From','Photo','Potential','Real Face','Special','Wage'])
fifa22_df=fifa22_df.drop(columns=['Club Logo','Flag','Jersey Number','Joined','Loaned From','Photo','Potential','Real Face','Special','Wage'])
fifa23_df=fifa23_df.drop(columns=['Club Logo','Flag','Kit Number','Joined','Loaned From','Photo','Potential','Real Face','Special','Wage'])
fifa21_df.to_csv(r'D:\Project4NUS\FIFA\FIFA_cleaned\21.csv', index=False)
fifa22_df.to_csv(r'D:\Project4NUS\FIFA\FIFA_cleaned\22.csv', index=False)
fifa23_df.to_csv(r'D:\Project4NUS\FIFA\FIFA_cleaned\23.csv', index=False)

# **3. Calculate the spearman correlation coefficient between Whoscored summary rating and FIFA overall rating**

**3.1 Clear newlines in Whoscored column 'name'**

In [32]:
#Clear newlines in Whoscored column 'name'
Whoscored_17['name']=[str(i).replace('\n ','') for i in Whoscored_17['name']]
Whoscored_18['name']=[str(i).replace('\n ','') for i in Whoscored_18['name']]
Whoscored_19['name']=[str(i).replace('\n ','') for i in Whoscored_19['name']]
Whoscored_20['name']=[str(i).replace('\n ','') for i in Whoscored_20['name']]
Whoscored_21['name']=[str(i).replace('\n ','') for i in Whoscored_21['name']]
Whoscored_22['name']=[str(i).replace('\n ','') for i in Whoscored_22['name']]
Whoscored_23['name']=[str(i).replace('\n ','') for i in Whoscored_23['name']]
merged_all['name']=[str(i).replace('\n ','') for i in merged_all['name']]

C:\Windows\Temp\ipykernel_25888\4082047224.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Whoscored_17['name']=[str(i).replace('\n ','') for i in Whoscored_17['name']]
C:\Windows\Temp\ipykernel_25888\4082047224.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Whoscored_18['name']=[str(i).replace('\n ','') for i in Whoscored_18['name']]
C:\Windows\Temp\ipykernel_25888\4082047224.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Whoscored_19['name']=[str(i).replace('\n ','') for i in Whoscored_19['name']]
C:\Windows\Temp\ipykernel_25888\4082047224.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Whoscored_20['name']=[str(i).replace('\n ','') for i in Whoscored_20['name']]
C:\Windows\Temp\ipykernel_25888\4082047224.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Whoscored_21['name']=[str(i).replace('\n ','') for i in Whoscored_21['name']]
C:\Windows\Temp\ipykernel_25888\4082047224.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Whoscored_22['name']=[str(i).replace('\n ','') for i in Whoscored_22['name']]
C:\Windows\Temp\ipykernel_25888\4082047224.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Whoscored_23['name']=[str(i).replace('\n ','') for i in Whoscored_23['name']]

## **3.2Match player names**

**3.2.1make sure charset of all data files is the same** (ALL are utf-8)

In [33]:
#make sure charset is the same.It is improtant to use with open(file,'rb') here to ensure file is read exactly as-is
import chardet
with open(r'D:\Project4NUS\Whoscored\raw\Whoscored_defensive.csv','rb') as file:
    result = chardet.detect(file.read())
    print(result['encoding'])
    
with open(r'D:\Project4NUS\Whoscored\raw\Whoscored_offensive.csv','rb') as file:
    result = chardet.detect(file.read())
    print(result['encoding'])

with open(r'D:\Project4NUS\Whoscored\raw\Whoscored_summary.csv','rb') as file:
    result = chardet.detect(file.read())
    print(result['encoding'])

utf-8
utf-8
utf-8

In [34]:
import pandas as pd
import re
pattern = r'^[a-zA-Z. ]+$'

#filter the rows whose value in name column is not english letter and '.'
invalid_rows= fifa20_df[~fifa20_df['Name'].str.match(pattern)]
invalid_rows_20_wh = Whoscored_20[~Whoscored_20['name'].str.match(pattern)]

print("Rows with invalid characters in FIFA 'Name' column:")
print(invalid_rows['Name'])
print("Rows with invalid characters in Whoscored 'name' column:")
print(invalid_rows_20_wh['name'])

Rows with invalid characters in FIFA 'Name' column:
0                 L. Suárez
4                  M. Acuña
10                L. Modri_
27                F. Kosti_
31        12_Roberto Carlos
                ...
17088           18_M. Bacon
17092          17_V. Frodig
17100         18_N. Krucker
17101         18_A. Viscovo
17103         07_A. Censori
Name: Name, Length: 4531, dtype: object
Rows with invalid characters in Whoscored 'name' column:
52             Ousmane Dembélé
142              Kylian Mbappé
171              Péter Gulácsi
179              Son Heung-Min
210                Lee Kang-In
                 ...
2765       Baptiste Santamaría
2794         Aaron Wan-Bissaka
2806             Álvaro García
2825           Pavel Kaderábek
2860                Unai López
Name: name, Length: 67, dtype: object

In [35]:
filtered_df = fifa20_df[fifa20_df['Name'].str.contains(r'^[^.]*$', regex=True)]
filtered_df_2 = fifa20_df[fifa20_df['Name'].str.contains('.')]

df=fifa20_df
df[['A','B']] = df['Name'].str.split('. ', n=1,expand=True)
df['B']=df['B'].fillna('')

df_with_spaces_in_B = df[df['B'].str.contains(' ', na=False)]

print(df_with_spaces_in_B['B'])

3           De Bruyne
45            de Jong
76           Di María
82           Lo Celso
111       van de Beek
             ...
16980       Vom Steeg
16986        Al Anazi
17040       Al Ghamdi
17048       St. Clair
17058    van den Berg
Name: B, Length: 708, dtype: object

**We discover that there are a few patterns for "weird name":
1.some names containing number in FIFA like "17_V. Frodig",these are virtual characters in the game.They have no influence on our result.
2.**

## **3.3 Calculate correlation coefficient for 'Best Overall Rating' in FIFA and 'Rating' in Whoscored'**

In [36]:
#FIFA use abbreviated first name and full last name for each player while Whoscored use full name.So to match each player,we first split their 
#name in FIFA through '.' matching their last name with those in Whoscored,then match the first letter of their first name
def dfmerge(data1,data2,year):
    df1,df2=data1.copy(),data2.copy()
    df1=df1[df1['Season'].str.startswith(str(year-1))]
    df1['name1'] = df1['name'].apply(lambda x: x.split()[0][0]+' '+ x.split()[-1])
    df2['name1'] = df2['Name'].apply(lambda x: x.split()[0][0]+' '+ x.split()[-1])
    df=pd.merge(df1,df2, on='name1',how='left')
    df=df.dropna()
    return df

def dfmerge1(data1,data2,year):
    df1,df2=data1.copy(),data2.copy()
    df1=df1[df1['Season'].str.startswith(str(year-1))]
    df1['name1'] = df1['name'].apply(lambda x: ' '.join(x.split()))  
    df1['name1'] = df1['name'].apply(lambda x: x.split()[0][0]+' '+ x.split()[-1])
    df2['name1'] = df2['Name'].apply(lambda x: ' '.join(x.split())) 
    df2['name1'] = df2['Name'].apply(lambda x: x.split()[0][0]+' '+ x.split()[-1])
    df=pd.merge(df1,df2, on='name1',how='left')
    df=df.dropna()
    return df

def pearsoncorr(df1,df2,col1,col2,year):
    x=merge_df[col1]
    y=merge_df[col2]
    return stats.pearsonr(x,y)

def spearmancorr(df1,df2,col1,col2,year,is_five_leagues):
    x=merge_df[col1]
    y=merge_df[col2]
    return stats.spearmanr(x,y)

In [338]:
merge17=dfmerge(merged_all,fifa17_df,2017)
print(merge17.shape[0])
x_17=merge17['Best Overall Rating']
y_17=merge17['Rating_summary']
print(stats.spearmanr(x_17,y_17))
print(stats.pearsonr(x_17,y_17))

118
SignificanceResult(statistic=0.5699844257832722, pvalue=1.6202495077772008e-11)
PearsonRResult(statistic=0.5953199003912175, pvalue=1.1620252377054957e-12)

In [339]:
merge18=dfmerge(merged_all,fifa18_df,2018)
print(merge18.shape[0])
x_18=merge18['Best Overall Rating']
y_18=merge18['Rating_summary']
print(stats.spearmanr(x_18,y_18))
print(stats.pearsonr(x_18,y_18))

134
SignificanceResult(statistic=0.4894577595551041, pvalue=1.955776751341911e-09)
PearsonRResult(statistic=0.5277342431954392, pvalue=5.673446020367692e-11)

In [396]:
merge19=dfmerge(merged_all,fifa19_df,2019)
print(merge19.shape[0])#Calculate how many records are used
x_19=merge19['Best Overall Rating']
y_19=merge19['Rating_summary']
print(stats.spearmanr(x_19,y_19))
print(stats.pearsonr(x_19,y_19))
print(merge19['Name'])
print(merge19['name'])

196
SignificanceResult(statistic=0.4871963134020752, pvalue=4.445386078242554e-13)
PearsonRResult(statistic=0.47887651034550877, pvalue=1.2495101257439131e-12)
0          G. Lo Celso
1          G. Lo Celso
2              H. Kane
4              B. Saka
5           O. Dembélé
            ...
249     C. Lykogiannis
250         M. de Roon
252           A. Gomes
254            D. Kohr
255          J. Brandt
Name: Name, Length: 196, dtype: object
0                Giovani Lo Celso
1                Giovani Lo Celso
2                      Harry Kane
4                     Bukayo Saka
5                 Ousmane Dembélé
                  ...
249       Charalampos Lykogiannis
250                Marten de Roon
252                   Angel Gomes
254                  Dominik Kohr
255                 Julian Brandt
Name: name, Length: 196, dtype: object